{
  "WorkItem": {
    "AffectedComponent": {
      "Name": "Library",
      "DisplayName": "Library"
    },
    "ClosedComment": "",
    "ClosedDate": "2016-02-24T07:40:16.563-08:00",
    "CommentCount": 0,
    "Custom": null,
    "Description": "Hi,\n\nSince I've updated to the latest stable release(2.5.4) I'm getting the following error:\n_The task has been configured with an unsupported combination of account settings and run time options. (Exception from HRESULT: 0x80041314)_\nThis did not happen with version 2.4.2 and lower (doublechecked it)\n\nWhat happens is:\nI'm contacting a Win7 machine but i specify the taskservice to use 1.1 version.\nThen i register a task with the serviceaccount.\nI've been able to reproduce this error several times\n\nCan you confirm this as a bug?\n\nCode (C#):\n```\nusing (TaskService ts = new TaskService(hostname, null, null, null, true))\n{\n   TaskDefinition tduser = ts.NewTask();\n   bool newVer = (ts.HighestSupportedVersion >= new Version(1, 2));\n   tduser.Actions.Add(new ExecAction(\"cmd\", \"Do something\", null));\n   tduser.Settings.DisallowStartIfOnBatteries = false;\n   tduser.Settings.StopIfGoingOnBatteries = false;\n   tduser.RegistrationInfo.Description = \"My Task\";\n   if (newVer) //v2.0 \n   {\n      tduser.Principal.RunLevel = TaskRunLevel.Highest;\n      tduser.Settings.AllowDemandStart = true;\n   }\n   ts.RootFolder.RegisterTaskDefinition(\"My Task\", tduser, TaskCreation.CreateOrUpdate,\n      \"system\", null, TaskLogonType.ServiceAccount); //this crashed\n   ts.GetTask(\"My Task\").Run();\n}\n```",
    "LastUpdatedDate": "2016-02-24T07:40:16.563-08:00",
    "PlannedForRelease": "Release 2.5.28",
    "ReleaseVisibleToPublic": true,
    "Priority": {
      "Name": "High",
      "Severity": 150,
      "Id": 3
    },
    "ProjectName": "taskscheduler",
    "ReportedDate": "2015-11-25T00:42:40.617-08:00",
    "Status": {
      "Name": "Closed",
      "Id": 4
    },
    "ReasonClosed": {
      "Name": "Fixed"
    },
    "Summary": "The task has been configured with an unsupported combination of account settings and run time options.",
    "Type": {
      "Name": "Issue",
      "Id": 3
    },
    "VoteCount": 1,
    "Id": 12293
  },
  "FileAttachments": [
    {
      "FileId": 5058,
      "FileName": "TaskSchedulerConfig.zip",
      "DownloadUrl": ".\\5058"
    }
  ],
  "Comments": [
    {
      "Message": "Corrected issue. Look for fix in forthcoming 2.5.5 release.",
      "PostedDate": "2015-11-28T19:38:18.743-08:00",
      "Id": -2147483648
    },
    {
      "Message": "Do you have an eta for that version?",
      "PostedDate": "2015-12-02T00:43:44.253-08:00",
      "Id": -2147483648
    },
    {
      "Message": "This weekend most likely. I'm also working on another bug for that release.",
      "PostedDate": "2015-12-02T07:35:30.72-08:00",
      "Id": -2147483648
    },
    {
      "Message": "",
      "PostedDate": "2015-12-07T14:30:59.24-08:00",
      "Id": -2147483648
    },
    {
      "Message": "Hi,\r\n\r\nThanks for the 2.5.5 update, however it does not seem to be working 100%.\r\n\r\nCould you please verify\n - When i connect from my local computer to my local computer => it works\n - When i connect from my local computer to a computer in our domain => it fails with the following msg\n   _The network path was not found. (Exception from HRESULT: 0x80070035)_\r\n\r\nPart where it crashes\n_using (TaskService ts = new TaskService(hostname, null, null, null, true))_",
      "PostedDate": "2015-12-08T00:56:15.93-08:00",
      "Id": -2147483648
    },
    {
      "Message": "** Closed by dahall 12/7/2015 2:30 PM",
      "PostedDate": "2015-12-08T00:57:01.407-08:00",
      "Id": -2147483648
    },
    {
      "Message": "",
      "PostedDate": "2015-12-08T00:57:01.497-08:00",
      "Id": -2147483648
    },
    {
      "Message": "",
      "PostedDate": "2015-12-08T00:57:15.107-08:00",
      "Id": -2147483648
    },
    {
      "Message": "Just to be clear, this was all working previous to 2.5.4 (2.4.x)? Connecting to Win7 via the v1 mode is much less reliable as it has to use a file share to access the tasks.",
      "PostedDate": "2015-12-09T22:45:21.307-08:00",
      "Id": -2147483648
    },
    {
      "Message": "This was indeed working.\r\n\r\nThe reason why i know this is because we have a subnet of Win 7 computer that all return version 1.1 while they should have the newer version (i know, it's crazy...)\r\n\r\nI used to be able to access the scheduler, but not anymore.\n",
      "PostedDate": "2015-12-14T06:25:47.86-08:00",
      "Id": -2147483648
    },
    {
      "Message": "",
      "PostedDate": "2016-02-07T09:55:39.81-08:00",
      "Id": -2147483648
    },
    {
      "Message": "Please try it again now with released version 2.5.13. Also, I have posted here a diagnostic tool. Will you run it on both the systems (host and client) and let me know the results you get?",
      "PostedDate": "2016-02-07T09:55:40.377-08:00",
      "Id": -2147483648
    },
    {
      "Message": "",
      "PostedDate": "2016-02-24T07:40:16.563-08:00",
      "Id": -2147483648
    }
  ]
}